### ISSUE TITLE
Why to connect USB C case to 1M resistor? 

### ISSUE THREAD

**Issue by nissimzur** [combs/USBC6P#2]
I believe for until EMI, the USB C case has to connect to GND.

**Comment by combs** [comment]
There are a lot of different opinions about this! Here's a [helpful summary](https://www.reddit.com/r/AskElectronics/comments/7in4a5/should_the_usb_connector_be_grounded/
) and [another](https://electronics.stackexchange.com/questions/389972/usb-shield-to-ground-or-not-to-ground).

My general takeaway was to ground the "host side" and decouple or high-ohm terminate the "device side" ports, to avoid any ground loops. but it varies based on your device cases and how each side is powered.

One interesting issue that Type-C raises is what should be done in case of ambidextrous ports? 
 
In the README I did make the assumption that this is a "device side" port, since it doesn't carry data lines and is likely to be connected to, say, a wall charger (which would be the "host side" and thus grounded). The schematic makes that assumption. But you could terminate, decouple, directly ground the port however you wish. The nice thing about leaving yourself a footprint is that you could always put a 0R resistor on it to directly short to ground.

**Comment by combs** [comment]
I updated the README.md with a little more nuance about this. Thanks!
